pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo 'Building'
            }
        }
        stage('Test'){
            steps{
                withGradle(){
                    bat 'C:/Windows/System32/config/systemprofile/AppData/Local/Jenkins/.jenkins/tools/hudson.plugins.gradle.GradleInstallation/Gradle6.3/bin/gradle clean test aggregate --scan --info'
                }
            }
        }
        stage('Deploy'){
            steps{
                  echo 'Deploying'
            }
        }
    }
    post {
            always {
                echo 'One way or another, I have finished'
                deleteDir() /* clean up our workspace */
            }
            success {
                echo 'Succeeded!'
            }
            unstable {
                echo 'The Pipeline is unstable'
            }
            failure {
                echo 'The Pipeline failed'
            }
            changed {
                echo 'The Pipeline changed'
            }
        }
}