pipeline{
    agent any
    stages{
        stage('Download code'){
                steps{
                    git 'https://github.com/seaalvar/appgateprueba.git'
                }
            }
        stage('Run test'){
            steps{
                withGradle(){
                    bat 'clean test --scan --info'
                }
            }
        }
    }
}