pipeline{
    agent any
    stages{
        stage('test'){
            steps{
                withGradle(gradle : 'Gradle6.3'){
                    sh 'clean test --scan --info'
                }
            }
        }
    }
}